# Generated by Django 4.2.2 on 2024-07-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='pleasant_habit_sigh',
            new_name='pleasant_habit_sign',
        ),
    ]
